# Generated by Django 3.0.5 on 2023-10-08 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('exchange', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('netrate', models.FloatField()),
                ('amount', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=10)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.Client')),
            ],
        ),
    ]
