# Generated by Django 3.0.5 on 2023-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
