# Generated by Django 3.0.5 on 2023-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0004_auto_20231010_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.FloatField(primary_key=True, serialize=False, unique=True),
        ),
    ]
