# Generated by Django 3.0.5 on 2023-10-10 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0005_auto_20231010_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.FloatField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0.0, message='Please enter a valid value. The two nearest valid values are 0 and 1.'), django.core.validators.MaxValueValidator(10, message='Please enter a valid value. The two nearest valid values are 0 and 1.')]),
        ),
    ]
