# Generated by Django 3.0.5 on 2023-10-10 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0008_auto_20231010_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='brokerage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001, message='Please enter a valid value. The two nearest valid values are 0.001 and 10.'), django.core.validators.MaxValueValidator(10, message='Please enter a valid value. The two nearest valid values are 0.001 and 10.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
