# Generated by Django 3.0.5 on 2023-10-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0012_auto_20231010_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.FloatField(),
        ),
    ]
