# Generated by Django 3.0.5 on 2023-10-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0013_auto_20231010_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.PositiveIntegerField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
